Feature/email
ParkGeonRyul/Eden_Back pull request #7
Opened 2024-01-23 06:42 UTC by minsu0717

- nodemailer를 사용한 이메일인증api 설계

인증번호를 db에 저장할건지????

인증번호를 service에 넣어야하는지

2024-01-31 07:42 UTC, suyeongs approved these changes
lgtm!

2024-01-31 14:08 UTC, Junjiii commented
lgtm

2024-02-04 16:01 UTC, ParkGeonRyul requested changes
Conflict가 나오는 상황이라 수정 부탁드립니다!

2024-02-06 07:48 UTC, ParkGeonRyul requested changes
custom error 기능 적용하여 수정 부탁드립니다.

2024-02-06 07:50 UTC, ParkGeonRyul requested changes
custom error 기능 적용하여 수정 부탁드립니다!

2024-02-21 08:46 UTC, ParkGeonRyul approved these changes
차후에 커스텀 에러 및 그 외의 기능들 제가 수정하겠습니다.

2024-02-21 08:46 UTC, merged